[project]
name = "wutheringwaves"
version = "0.1.0"
description = "Wuthering Waves archive"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["aiofiles", "html-sanitizer", "httpx", "markupsafe"]
